[pytest]
DJANGO_SETTINGS_MODULE = sabe.config.settings.test
python_files = tests.py test_*.py
testpaths = sabe tests
addopts = --nomigrations -v --cov=sabe --cov-report=term-missing --cov-report=html:htmlcov
